[project]
name = "rag-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.1",
    "ollama>=0.6.0",
    "pymilvus>=2.6.3",
    "pymilvus-model>=0.3.2",
]
